Repository fedora-infra/asknot-ng, pull requests merged in 2023-11, with the labels that each got.

#169 Update link to GNOME source
  questions/includes/fedora/coding/c.yml
Labels: bug, GNOME

#164 Replace dead links
  questions/includes/fedora/community.yml
Labels: bug

#167 Update Old Links
  questions/includes/fedora/translation.yml
Labels: bug

#168 Remove Closed Projects
  l10n/fedora/locale/ar.po
  l10n/fedora/locale/asknot-ng.pot
  l10n/fedora/locale/ca.po
  l10n/fedora/locale/cs.po
  l10n/fedora/locale/de.po
  l10n/fedora/locale/en_GB.po
  l10n/fedora/locale/es.po
  l10n/fedora/locale/fi.po
  l10n/fedora/locale/fr.po
  l10n/fedora/locale/gu.po
  l10n/fedora/locale/he.po
  l10n/fedora/locale/hu.po
  l10n/fedora/locale/id.po
  l10n/fedora/locale/it.po
  l10n/fedora/locale/ja.po
  l10n/fedora/locale/ko.po
  l10n/fedora/locale/nl.po
  l10n/fedora/locale/pt.po
  l10n/fedora/locale/pt_BR.po
  l10n/fedora/locale/ru.po
  l10n/fedora/locale/si.po
  l10n/fedora/locale/sq.po
  l10n/fedora/locale/sv.po
  l10n/fedora/locale/tr.po
  l10n/fedora/locale/uk.po
  l10n/fedora/locale/zh_CN.po
  questions/includes/fedora/qa.yml
  questions/includes/fedora/writing.yml
Labels: enhancement

#171 Updated questions links
  questions/includes/fedora/coding/c++.yml
  questions/includes/fedora/coding/c.yml
  questions/includes/fedora/coding/java.yml
  questions/includes/fedora/coding/python.yml
  questions/includes/fedora/coding/web.yml
  questions/includes/fedora/community.yml
  questions/includes/fedora/design.yml
  questions/includes/fedora/translation.yml
  questions/includes/fedora/writing.yml
Labels: enhancement
